/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlertState } from './alert-state'

/**
 * Properties of a Alert
 * @export
 * @interface Alert
 */
export interface Alert {
  /**
   * Short ID
   * @type {string}
   * @memberof Alert
   */
  id: string
  /**
   *
   * @type {VDN}
   * @memberof Alert
   */
  name: string
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Alert
   */
  created_at: string
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Alert
   */
  state_updated_at: string
  /**
   *
   * @type {AlertState}
   * @memberof Alert
   */
  state: AlertState
}
