/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkID } from './network-id'

/**
 * On-chain asset (aka token)
 * @export
 * @interface Asset
 */
export interface Asset {
  /**
   * Assets\'s on-chain address (optional)
   * @type {string}
   * @memberof Asset
   */
  address?: string
  /**
   * Asset\'s decimal places
   * @type {number}
   * @memberof Asset
   */
  decimals: number
  /**
   * Asset\'s name
   * @type {string}
   * @memberof Asset
   */
  name: string
  /**
   *
   * @type {NetworkID}
   * @memberof Asset
   */
  network_id: NetworkID
  /**
   * Asset\'s symbol
   * @type {string}
   * @memberof Asset
   */
  symbol: string
}
