/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Properties of an ErrorDescription
 * @export
 * @interface ErrorDescriptor
 */
export interface ErrorDescriptor {
  /**
   * Error message
   * @type {string}
   * @memberof ErrorDescriptor
   */
  message: string
  /**
   * Error title
   * @type {string}
   * @memberof ErrorDescriptor
   */
  title: string
  /**
   * Error type
   * @type {string}
   * @memberof ErrorDescriptor
   */
  type: string
}
