/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubfunctionSpec } from './subfunction-spec'

/**
 * A root function specification
 * @export
 * @interface FunctionSpec
 */
export interface FunctionSpec {
  /**
   * Default subfunction name
   * @type {string}
   * @memberof FunctionSpec
   */
  default: string
  /**
   * Function description
   * @type {string}
   * @memberof FunctionSpec
   */
  description: string
  /**
   * Function mnemonic
   * @type {string}
   * @memberof FunctionSpec
   */
  mnemonic: string | null
  /**
   * Function name
   * @type {string}
   * @memberof FunctionSpec
   */
  name: string
  /**
   *
   * @type {Array<SubfunctionSpec>}
   * @memberof FunctionSpec
   */
  subfunctions: Array<SubfunctionSpec>
}
