/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Unique Identifier
 * @export
 * @interface ID
 */
export interface ID {
  /**
   * Universally unique identifier - UUID V4
   * @type {string}
   * @memberof ID
   */
  id: string
}
