/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Blockchain } from './blockchain'
import { NetworkMode } from './network-mode'

/**
 * Common properties of a Label (required)
 * @export
 * @interface LabelCommonRequired
 */
export interface LabelCommonRequired {
  /**
   *
   * @type {Blockchain}
   * @memberof LabelCommonRequired
   */
  blockchain: Blockchain
  /**
   * Unique name to identify the Label
   * @type {string}
   * @memberof LabelCommonRequired
   */
  name: string
  /**
   *
   * @type {NetworkMode}
   * @memberof LabelCommonRequired
   */
  network_mode: NetworkMode
  /**
   * Label\'s value
   * @type {string}
   * @memberof LabelCommonRequired
   */
  value: string
}
