/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Common properties of a Label schema
 * @export
 * @interface LabelCommon
 */
export interface LabelCommon {
  /**
   * Unique name to identify the Label
   * @type {string}
   * @memberof LabelCommon
   */
  name: string
  /**
   * Network
   * @type {string}
   * @memberof LabelCommon
   */
  network: string
  /**
   * Label\'s address
   * @type {string}
   * @memberof LabelCommon
   */
  address?: string
}
