/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkMode } from './network-mode'

/**
 * Common properties of a Label (optional)
 * @export
 * @interface LabelCommonOptional
 */
export interface LabelCommonOptional {
  /**
   * Label\'s address
   * @type {string}
   * @memberof LabelCommonOptional
   */
  address?: string
  /**
   * Unique name to identify the Label
   * @type {string}
   * @memberof LabelCommonOptional
   */
  name?: string
  /**
   *
   * @type {NetworkMode}
   * @memberof LabelCommonOptional
   */
  network_mode?: NetworkMode
}
