/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LabelCommonOptional } from './label-common-optional'

/**
 * @type LabelUpdateRequest
 * Request to update a label
 * @export
 */
export type LabelUpdateRequest = LabelCommonOptional
