/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LabelCommonRequired } from './label-common-required'
import { ResourceCommon } from './resource-common'

/**
 * @type Label
 * Identifier to easily reference an Address or Transaction
 * @export
 */
export type Label = LabelCommonRequired & ResourceCommon
