/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDN } from './vdn'

/**
 * Properties of a LocalFunctionCall
 * @export
 * @interface LocalFunctionCall
 */
export interface LocalFunctionCall {
  /**
   * LocalFunctionCall function
   * @type {string}
   * @memberof LocalFunctionCall
   */
  function: string

  /**
   * LocalFunctionCall subfunction
   * @type {string}
   * @memberof LocalFunctionCall
   */
  subfunction: string

  /**
   * LocalFunctionCall arguments
   * @type {Array<VDN>}
   * @memberof LocalFunctionCall
   */
  args: VDN[]

  /**
   * LocalFunctionCall options
   * @type {Record<string, VDN>}
   * @memberof LocalFunctionCall
   */
  options: Record<string, VDN>
}
