/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response containing user\'s details to call authenticated endpoints
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   * User\'s authentication token
   * @type {string}
   * @memberof LoginResponse
   */
  token: string
  /**
   * Universally unique identifier - UUID V4
   * @type {string}
   * @memberof LoginResponse
   */
  user_id: string
}
