/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to login
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
  /**
   * User\'s email address
   * @type {string}
   * @memberof LoginRequest
   */
  email: string
  /**
   * User\'s password
   * @type {string}
   * @memberof LoginRequest
   */
  password: string
}
