/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Blockchain } from './blockchain'
import { Network } from './network'

/**
 * Tuple to identify a blockchain:network pair
 * @export
 * @interface NetworkID
 */
export interface NetworkID {
  /**
   *
   * @type {Blockchain}
   * @memberof NetworkID
   */
  blockchain: Blockchain
  /**
   *
   * @type {Network}
   * @memberof NetworkID
   */
  network: Network
}
