/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Tuple to identify a blockchain:network pair
 * @export
 * @interface NetworkID
 */
export interface NetworkID {
  /**
   * Blockchain
   * @type {string}
   * @memberof NetworkID
   */
  blockchain: string
  /**
   * Blockchain\'s network
   * @type {string}
   * @memberof NetworkID
   */
  network: string
}
