/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkMode } from './network-mode'

/**
 * Properties of a Session
 * @export
 * @interface Session
 */
export interface Session {
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Session
   */
  created_at: string
  /**
   * Universally unique identifier - UUID V4
   * @type {string}
   * @memberof Session
   */
  id: string
  /**
   * Unique name to identify the Session
   * @type {string}
   * @memberof Session
   */
  name: string
  /**
   *
   * @type {NetworkMode}
   * @memberof Session
   */
  network_mode: NetworkMode
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Session
   */
  updated_at: string
}
