/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Signature } from './signature'
import { TransacionHash } from './transacion-hash'

/**
 * @type SignatureOrTransactionHash
 * Signature or Transaction Hash
 * @export
 */
export type SignatureOrTransactionHash = Signature | TransacionHash
