/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object grouping pagination parameters.
 * @export
 * @interface StreamPagination
 */
export interface StreamPagination {
  /**
   * Maximum number of entries to be returned (max = 250)
   * @type {number}
   * @memberof StreamPagination
   */
  limit: number
  /**
   * Initial position from which to take entries (0-indexed).
   * @type {number}
   * @memberof StreamPagination
   */
  offset: number
  /**
   * The total number of entries the list holds.
   * @type {number}
   * @memberof StreamPagination
   */
  total_count: number | null
}
