/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StreamState } from './stream-state'

/**
 * Properties for patching a stream
 * @export
 * @interface StreamPatchParams
 */
export interface StreamPatchParams {
  /**
   * Maximum number of entries to be returned (max = 250)
   * @type {number}
   * @memberof StreamPatchParams
   */
  limit?: number
  /**
   * Initial position from which to take entries (0-indexed).
   * @type {number}
   * @memberof StreamPatchParams
   */
  offset?: number
  /**
   *
   * @type {StreamState}
   * @memberof StreamPatchParams
   */
  state?: StreamState
}
