/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VXLType } from './vxltype'

/**
 * A VXL struct type specification
 * @export
 * @interface StructSpec
 */
export interface StructSpec {
  /**
   * A map of field names and their types
   * @type {{ [key: string]: VXLType; }}
   * @memberof StructSpec
   */
  fields: { [key: string]: VXLType }
  /**
   * Struct name
   * @type {string}
   * @memberof StructSpec
   */
  type: string
}
