/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A subfunction\'s option
 * @export
 * @interface SubfunctionOption
 */
export interface SubfunctionOption {
  /**
   * Default value if not provided
   * @type {string}
   * @memberof SubfunctionOption
   */
  default: string
  /**
   * Option description
   * @type {string}
   * @memberof SubfunctionOption
   */
  description: string
  /**
   * Option name
   * @type {string}
   * @memberof SubfunctionOption
   */
  name: string
  /**
   * Option type
   * @type {string}
   * @memberof SubfunctionOption
   */
  type: string
}
