/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VXLType } from './vxltype'

/**
 * A subfunction\'s parameter
 * @export
 * @interface SubfunctionParameter
 */
export interface SubfunctionParameter {
  /**
   * Parameter description
   * @type {string}
   * @memberof SubfunctionParameter
   */
  description: string
  /**
   * Parameter index
   * @type {number}
   * @memberof SubfunctionParameter
   */
  index?: number
  /**
   * Parameter name
   * @type {string}
   * @memberof SubfunctionParameter
   */
  name: string
  /**
   *
   * @type {VXLType}
   * @memberof SubfunctionParameter
   */
  type: VXLType
}
