/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubfunctionOption } from './subfunction-option'
import { SubfunctionParameter } from './subfunction-parameter'
import { VXLType } from './vxltype'

/**
 * A subfunction specification
 * @export
 * @interface SubfunctionSpec
 */
export interface SubfunctionSpec {
  /**
   * Subfunction description
   * @type {string}
   * @memberof SubfunctionSpec
   */
  description: string
  /**
   * Usage example
   * @type {string}
   * @memberof SubfunctionSpec
   */
  example?: string
  /**
   * Subfunction name
   * @type {string}
   * @memberof SubfunctionSpec
   */
  name: string
  /**
   *
   * @type {Array<SubfunctionOption>}
   * @memberof SubfunctionSpec
   */
  options: Array<SubfunctionOption>
  /**
   *
   * @type {Array<SubfunctionParameter>}
   * @memberof SubfunctionSpec
   */
  parameters: Array<SubfunctionParameter>
  /**
   *
   * @type {VXLType}
   * @memberof SubfunctionSpec
   */
  returns: VXLType
}
