/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const ALL_FUNCTION_PARAMETER_TYPES = [
  'address',
  'asset',
  'blockchain',
  'currency',
  'decimal',
  'function',
  'integer',
  'label',
  'boolean',
  'portfolio',
  'string',
  'workspace',
]

export type FunctionParameterType = typeof ALL_FUNCTION_PARAMETER_TYPES[number]

/**
 * A subfunction\'s parameter
 * @export
 * @interface SubfunctionParameter
 */
export interface SubfunctionParameter {
  /**
   * Parameter description
   * @type {string}
   * @memberof SubfunctionParameter
   */
  description: string
  /**
   * Parameter name
   * @type {string}
   * @memberof SubfunctionParameter
   */
  name: string
  /**
   * Parameter type
   * @type {FunctionParameterType}
   * @memberof SubfunctionParameter
   */
  type: FunctionParameterType
}
