/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Resource timestamps
 * @export
 * @interface Timestamps
 */
export interface Timestamps {
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Timestamps
   */
  created_at: string
  /**
   * ISO8601 Timestamp
   * @type {string}
   * @memberof Timestamps
   */
  updated_at: string
}
