/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single transaction hash
 * @export
 * @interface TransacionHash
 */
export interface TransacionHash {
  /**
   * Transaction Hash
   * @type {string}
   * @memberof TransacionHash
   */
  transaction_hash: string
}
