/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VXLType } from './vxltype'

/**
 * A subfunction\'s option
 * @export
 * @interface UnionType
 */
export interface UnionType {
  /**
   *
   * @type {string}
   * @memberof UnionType
   */
  type: 'union'
  /**
   * array of concrete types
   * @type {Array<string>}
   * @memberof UnionType
   */
  types: VXLType[]
}

export const isUnionType = (type: VXLType): type is UnionType =>
  typeof type === 'object' && type.type === 'union' && typeof type.types === 'object'
