/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A subfunction\'s option
 * @export
 * @interface UnionType
 */
export interface UnionType {
  /**
   *
   * @type {string}
   * @memberof UnionType
   */
  type: UnionTypeTypeEnum
  /**
   * array of concrete types
   * @type {Array<string>}
   * @memberof UnionType
   */
  types: Array<string>
}

export const UnionTypeTypeEnum = {
  Union: 'union',
} as const

export type UnionTypeTypeEnum = typeof UnionTypeTypeEnum[keyof typeof UnionTypeTypeEnum]
