/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ALL_VDN_ERRORS } from '.'
import { VDNAddress } from './vdnaddress'
import { VDNAsset } from './vdnasset'
import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNBoolean } from './vdnboolean'
import { VDNDateTime } from './vdndate-time'
import { VDNDecimal } from './vdndecimal'
import { VDNEither } from './vdneither'
import { VDNError } from './vdnerror'
import { VDNInteger } from './vdninteger'
import { VDNLabel } from './vdnlabel'
import { VDNList } from './vdnlist'
import { VDNMap } from './vdnmap'
import { VDNString } from './vdnstring'
import { VDNSymbol } from './vdnsymbol'
import { VDNTask } from './vdntask'
import { VDNTransactionHash } from './vdntransaction-hash'
import { VDNURL } from './vdnurl'
import { VDNVenue } from './vdnvenue'
import { VDNVenueType } from './vdnvenue-type'

/**
 * @type VDN
 * VXL data notation
 * @export
 */
export type VDN =
  | VDNAddress
  | VDNAsset
  | VDNAssetSymbol
  | VDNBlockchain
  | VDNBoolean
  | VDNDateTime
  | VDNDecimal
  | VDNEither
  | VDNError
  | VDNInteger
  | VDNLabel
  | VDNList
  | VDNMap
  | VDNString
  | VDNSymbol
  | VDNTask
  | VDNTransactionHash
  | VDNURL
  | VDNVenue
  | VDNVenueType
  | VDNTransactionHash
  | VDNURL
  | VDNVenue
  | VDNVenueType

export type VDNType = VDN['type']
export type VDNValue = VDN['value']

export const isVDN = (vdn: VDN): vdn is VDN => vdn.type !== undefined && vdn.value !== undefined
export const isVDNError = (vdn: unknown): vdn is VDNError =>
  isVDN(vdn as VDNError) && ALL_VDN_ERRORS.indexOf((vdn as VDNError).type) !== -1
