/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNList } from './vdnlist'
import { VDNNone } from './vdnnone'
import { VDNPercentage } from './vdnpercentage'

/**
 *
 * @export
 * @interface VDNAPYValue
 */
export interface VDNAPYValue {
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNAPYValue
   */
  avg_30d: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNAPYValue
   */
  base: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNAPYValue
   */
  reward: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNList}
   * @memberof VDNAPYValue
   */
  reward_assets: VDNList
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNAPYValue
   */
  total: VDNPercentage | VDNNone
}
