/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL alert_state representation
 * @export
 * @interface VDNAlertState
 */
export interface VDNAlertState {
  /**
   *
   * @type {string}
   * @memberof VDNAlertState
   */
  type: VDNAlertStateTypeEnum
  /**
   *
   * @type {string}
   * @memberof VDNAlertState
   */
  value: string
}

export const VDNAlertStateTypeEnum = {
  AlertState: 'alert_state',
} as const

export type VDNAlertStateTypeEnum = typeof VDNAlertStateTypeEnum[keyof typeof VDNAlertStateTypeEnum]
