/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAPYValue } from './vdnapyvalue'
import { VDNBase } from './vdnbase'

/**
 * VXL apy representation
 * @export
 * @interface VDNAPY
 */
export interface VDNAPY extends VDNBase {

  /**
   *
   * @type {string}
   * @memberof VDNAPY
   */
  type: 'apy'
  /**
   *
   * @type {VDNAPYValue}
   * @memberof VDNAPY
   */
  value: VDNAPYValue
}
