/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL base type to inherit from
 * @export
 * @interface VDNAction
 */
export interface VDNAction {
    /**
     *
     * @type {string}
     * @memberof VDNAction
     */
    name: string

    /**
     *
     * @type {string}
     * @memberof VDNAction
     */
    vxl: string
}
