/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAlertState } from './vdnalert-state'
import { VDNDateTime } from './vdndate-time'
import { VDNNone } from './vdnnone'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNAlertValue
 */
export interface VDNAlertValue {
  /**
   *
   * @type {VDNDateTime}
   * @memberof VDNAlertValue
   */
  created_at: VDNDateTime
  /**
   *
   * @type {VDNString}
   * @memberof VDNAlertValue
   */
  expression: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNAlertValue
   */
  id: VDNString
  /**
   *
   * @type {VDNAlertValueName}
   * @memberof VDNAlertValue
   */
  name: VDNString | VDNNone
  /**
   *
   * @type {VDNAlertState}
   * @memberof VDNAlertValue
   */
  state: VDNAlertState
  /**
   *
   * @type {VDNDateTime}
   * @memberof VDNAlertValue
   */
  state_updated_at: VDNDateTime
}
