/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetValueAddress } from './vdnasset-value-address'
import { VDNAssetValueSymbol } from './vdnasset-value-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNBoolean } from './vdnboolean'
import { VDNInteger } from './vdninteger'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNAssetValue
 */
export interface VDNAssetValue {
  /**
   *
   * @type {VDNAssetValueAddress}
   * @memberof VDNAssetValue
   */
  address: VDNAssetValueAddress
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNAssetValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNAssetValue
   */
  decimals: VDNInteger
  /**
   *
   * @type {VDNString}
   * @memberof VDNAssetValue
   */
  name: VDNString
  /**
   *
   * @type {VDNBoolean}
   * @memberof VDNAssetValue
   */
  registered: VDNBoolean
  /**
   *
   * @type {VDNAssetValueSymbol}
   * @memberof VDNAssetValue
   */
  symbol: VDNAssetValueSymbol
}
