/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNAssetValue } from './vdnasset-value'

/**
 * VXL asset representation
 * @export
 * @interface VDNAsset
 */
export interface VDNAsset extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNAsset
   */
  type: 'asset'
  /**
   *
   * @type {VDNAssetValue}
   * @memberof VDNAsset
   */
  value: VDNAssetValue
}
