/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAddress } from './vdnaddress'
import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNInteger } from './vdninteger'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNAssetValue
 */
export interface VDNAssetValue {
  /**
   *
   * @type {VDNAddress}
   * @memberof VDNAssetValue
   */
  address: VDNAddress
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNAssetValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNAssetValue
   */
  decimals: VDNInteger
  /**
   *
   * @type {VDNString}
   * @memberof VDNAssetValue
   */
  name: VDNString
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNAssetValue
   */
  symbol: VDNAssetSymbol
}
