/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNAlertValue } from './vdnalert-value'

/**
 * VXL alert representation
 * @export
 * @interface VDNAlert
 */
export interface VDNAlert extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNAlert
   */
  type: 'alert'
  /**
   *
   * @type {VDNAlertValue}
   * @memberof VDNAlert
   */
  value: VDNAlertValue
}
