/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNInteger } from './vdninteger'
import { VDNString } from './vdnstring'
import { VDNURL } from './vdnurl'

/**
 *
 * @export
 * @interface VDNBlockchainValue
 */
export interface VDNBlockchainValue {
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNBlockchainValue
   */
  chain_id: VDNInteger
  /**
   *
   * @type {VDNURL}
   * @memberof VDNBlockchainValue
   */
  explorer: VDNURL
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockchainValue
   */
  name: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockchainValue
   */
  network: VDNString
}
