/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdn-base'
import { VDNBalanceValue } from './vdnbalance-value'

/**
 * VXL balance representation
 * @export
 * @interface VDNBalance
 */
export interface VDNBalance extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNBalance
   */
  type: 'balance'
  /**
   *
   * @type {VDNBalanceValue}
   * @memberof VDNBalance
   */
  value: VDNBalanceValue
}
