/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdn-base'
import { VDNBlockValue } from './vdnblock-value'

/**
 * VXL block representation
 * @export
 * @interface VDNBlock
 */
export interface VDNBlock extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNBlock
   */
  type: 'block'
  /**
   *
   * @type {VDNBlockValue}
   * @memberof VDNBlock
   */
  value: VDNBlockValue
}
