/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL boolean representation
 * @export
 * @interface VDNBoolean
 */
export interface VDNBoolean {
  /**
   *
   * @type {string}
   * @memberof VDNBoolean
   */
  type: 'boolean'
  /**
   *
   * @type {boolean}
   * @memberof VDNBoolean
   */
  value: boolean
}
