/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNBorrowAccountValue
 */
export interface VDNBorrowAccountValue {
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowAccountValue
   */
  available_borrow: VDNDecimal
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNBorrowAccountValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowAccountValue
   */
  health_factor: VDNDecimal
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNBorrowAccountValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNBorrowAccountValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowAccountValue
   */
  total_collateral: VDNDecimal
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowAccountValue
   */
  total_debt: VDNDecimal
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNBorrowAccountValue
   */
  venue: VDNVenue
}
