/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBorrowMarket } from './vdnborrow-market'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'

/**
 *
 * @export
 * @interface VDNBorrowPositionValue
 */
export interface VDNBorrowPositionValue {
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowPositionValue
   */
  debt_amount: VDNDecimal
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNBorrowPositionValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNBorrowMarket}
   * @memberof VDNBorrowPositionValue
   */
  market: VDNBorrowMarket
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNBorrowPositionValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBorrowPositionValue
   */
  value: VDNDecimal
}
