/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBorrowAccountValue } from './vdnborrow-account-value'

/**
 * VXL borrow_account representation
 * @export
 * @interface VDNBorrowAccount
 */
export interface VDNBorrowAccount {
  /**
   *
   * @type {string}
   * @memberof VDNBorrowAccount
   */
  type: VDNBorrowAccountTypeEnum
  /**
   *
   * @type {VDNBorrowAccountValue}
   * @memberof VDNBorrowAccount
   */
  value: VDNBorrowAccountValue
}

export const VDNBorrowAccountTypeEnum = {
  BorrowAccount: 'borrow_account',
} as const

export type VDNBorrowAccountTypeEnum = typeof VDNBorrowAccountTypeEnum[keyof typeof VDNBorrowAccountTypeEnum]
