/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNBlockchainValue
 */
export interface VDNBlockchainValue {
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockchainValue
   */
  blockchain: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockchainValue
   */
  network: VDNString
}
