/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNBridgeQuoteValue } from './vdnbridge-quote-value'

/**
 * VXL bridge_quote representation
 * @export
 * @interface VDNBridgeQuote
 */
export interface VDNBridgeQuote extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNBridgeQuote
   */
  type: 'bridge_quote'
  /**
   *
   * @type {VDNBridgeQuoteValue}
   * @memberof VDNBridgeQuote
   */
  value: VDNBridgeQuoteValue
}
