/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNFee } from './vdnfee'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNBuyQuoteValue
 */
export interface VDNBuyQuoteValue {
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNBuyQuoteValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNFee}
   * @memberof VDNBuyQuoteValue
   */
  network_fee_est: VDNFee
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBuyQuoteValue
   */
  receive_amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNBuyQuoteValue
   */
  receive_asset: VDNAsset
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBuyQuoteValue
   */
  spend_amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNBuyQuoteValue
   */
  spend_asset: VDNAsset
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNBuyQuoteValue
   */
  venue: VDNVenue
}
