/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'

/**
 *
 * @export
 * @interface VDNBalanceValue
 */
export interface VDNBalanceValue {
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBalanceValue
   */
  amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNBalanceValue
   */
  asset: VDNAsset
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNBalanceValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNBalanceValue
   */
  label: VDNLabel
}
