/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAction } from "./vdnaction"

/**
 * VXL base type to inherit from
 * @export
 * @interface VDNBase
 */
export interface VDNBase {
    /**
     *
     * @type {string}
     * @memberof VDNBase
     */
    parent_type: string | null

    /**
     *
     * @type {VDNAction}
     * @memberof VDNBase
     */
    actions?: VDNAction[]
}
