/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VDNBorrowPositionValue } from './vdnborrow-position-value';

/**
 * VXL lend_borrowed representation
 * @export
 * @interface VDNBorrowPosition
 */
export interface VDNBorrowPosition {
  /**
   *
   * @type {string}
   * @memberof VDNBorrowPosition
   */
  type: 'borrow_position'
  /**
   *
   * @type {VDNBorrowPositionValue}
   * @memberof VDNBorrowPosition
   */
  value: VDNBorrowPositionValue
}
