/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBlockchain } from './vdnblockchain'
import { VDNDateTime } from './vdndate-time'
import { VDNInteger } from './vdninteger'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNBlockValue
 */
export interface VDNBlockValue {
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNBlockValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockValue
   */
  hash: VDNString
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNBlockValue
   */
  number: VDNInteger
  /**
   *
   * @type {VDNString}
   * @memberof VDNBlockValue
   */
  parent_hash: VDNString
  /**
   *
   * @type {VDNDateTime}
   * @memberof VDNBlockValue
   */
  timestamp: VDNDateTime
}
