/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNDecimal } from './vdndecimal'
import { VDNFee } from './vdnfee'
import { VDNInteger } from './vdninteger'
import { VDNString } from './vdnstring'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNBridgeQuoteValue
 */
export interface VDNBridgeQuoteValue {
  /**
   *
   * @type {VDNFee}
   * @memberof VDNBridgeQuoteValue
   */
  network_fee_est: VDNFee
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBridgeQuoteValue
   */
  receive_amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNBridgeQuoteValue
   */
  receive_asset: VDNAsset
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNBridgeQuoteValue
   */
  receive_time_est: VDNInteger
  /**
   *
   * @type {VDNString}
   * @memberof VDNBridgeQuoteValue
   */
  route: VDNString
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNBridgeQuoteValue
   */
  send_amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNBridgeQuoteValue
   */
  send_asset: VDNAsset
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNBridgeQuoteValue
   */
  venue: VDNVenue
}
