/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNQuoteValue } from './vdn-quote-value'

/**
 * VXL buy_quote representation
 * @export
 * @interface VDNBuyQuote
 */
export interface VDNBuyQuote {
  /**
   *
   * @type {string}
   * @memberof VDNBuyQuote
   */
  type: 'buy_quote'
  /**
   *
   * @type {VDNQuoteValue}
   * @memberof VDNBuyQuote
   */
  value: VDNQuoteValue
}
