/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBorrowQuoteValue } from './vdnborrow-quote-value'

/**
 * VXL borrow_quote representation
 * @export
 * @interface VDNBorrowQuote
 */
export interface VDNBorrowQuote {
  /**
   *
   * @type {string}
   * @memberof VDNBorrowQuote
   */
  type: 'borrow_quote'
  /**
   *
   * @type {VDNBorrowQuoteValue}
   * @memberof VDNBorrowQuote
   */
  value: VDNBorrowQuoteValue
}
