/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VDNString } from './vdnstring';

/**
 * 
 * @export
 * @interface VDNChangesetErrorValue
 */
export interface VDNChangesetErrorValue {
    /**
     * 
     * @type {VDNString}
     * @memberof VDNChangesetErrorValue
     */
    'error': VDNString;
    /**
     * 
     * @type {VDNString}
     * @memberof VDNChangesetErrorValue
     */
    'field': VDNString;
}

