/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VDNBase } from './vdnbase';
import { VDNChangesetErrorValue } from './vdnchangeset-error-value';

/**
 * VXL changeset_error representation
 * @export
 * @interface VDNChangesetError
 */
export interface VDNChangesetError extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNChangesetError
   */
  type: 'changeset_error'
  /**
   *
   * @type {VDNChangesetErrorValue}
   * @memberof VDNChangesetError
   */
  value: VDNChangesetErrorValue
}
