/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBoolean } from './vdnboolean'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNCSVValue
 */
export interface VDNCSVValue {
  /**
   *
   * @type {VDNString}
   * @memberof VDNCSVValue
   */
  contents: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNCSVValue
   */
  decimal_sep: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNCSVValue
   */
  field_sep: VDNString
  /**
   *
   * @type {VDNBoolean}
   * @memberof VDNCSVValue
   */
  force_escaping: VDNBoolean
  /**
   *
   * @type {VDNString}
   * @memberof VDNCSVValue
   */
  line_sep: VDNString
  /**
   *
   * @type {VDNString}
   * @memberof VDNCSVValue
   */
  na_repr: VDNString
}
