/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL datetime representation
 * @export
 * @interface VDNDateTime
 */
export interface VDNDateTime {
  /**
   *
   * @type {string}
   * @memberof VDNDateTime
   */
  type: VDNDateTimeTypeEnum
  /**
   *
   * @type {string}
   * @memberof VDNDateTime
   */
  value: string
}

/**
 * @export
 * @enum {string}
 */
export enum VDNDateTimeTypeEnum {
  DateTime = 'date_time',
}
