/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDN } from './vdn'

/**
 * VXL Either representation
 * @export
 * @interface VDNEither
 */
export interface VDNEither {
  /**
   *
   * @type {string}
   * @memberof VDNEither
   */
  constructor: 'left' | 'right'
  /**
   *
   * @type {string}
   * @memberof VDNEither
   */
  type: 'either'
  /**
   *
   * @type {VDN}
   * @memberof VDNEither
   */
  value: VDN
}
