/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDN } from "./vdn"

/**
 * VXL error representation
 * @export
 * @interface VDNError
 */
export interface VDNError {
  /**
   *
   * @type {string}
   * @memberof VDNError
   */
  type: string

  /**
   * Error values
   */
  value: Record<string, VDN>
}
