/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL error representation
 * @export
 * @interface VDNError
 */
export interface VDNError {
  /**
   *
   * @type {string}
   * @memberof VDNError
   */
  type: VDNErrorTypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum VDNErrorTypeEnum {
  GasLimitReachedError = 'gas_limit_reached_error',
  GasUint64OverflowError = 'gas_uint64_overflow_error',
  InsufficientFundsError = 'insufficient_funds_error',
  InsufficientFundsForTransferError = 'insufficient_funds_for_transfer_error',
  IntrinsicGasTooLowError = 'intrinsic_gas_too_low_error',
  FeeCapVeryHighError = 'fee_cap_very_high_error',
  FeeCapTooLowError = 'fee_cap_too_low_error',
  TipVeryHighError = 'tip_very_high_error',
  TipAboveFeeCapError = 'tip_above_fee_cap_error',
  NonceTooHighError = 'nonce_too_high_error',
  NonceTooLowError = 'nonce_too_low_error',
  SenderNotEoaError = 'sender_not_eoa_error',
  RuntimeError = 'runtime_error',
  BuildError = 'build_error',
  BroadcastError = 'broadcast_error',
  InvalidAssetError = 'invalid_asset_error',
  NonPositiveAmountError = 'non_positive_amount_error',
}
