/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNDecimal } from './vdndecimal'

/**
 *
 * @export
 * @interface VDNFeeValue
 */
export interface VDNFeeValue {
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNFeeValue
   */
  amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNFeeValue
   */
  asset: VDNAsset
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNFeeValue
   */
  cost: VDNDecimal
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNFeeValue
   */
  quote_asset: VDNAssetSymbol
}
