/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNFeeValue } from './vdnfee-value'

/**
 * VXL fee representation
 * @export
 * @interface VDNFee
 */
export interface VDNFee extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNFee
   */
  type: 'fee'
  /**
   *
   * @type {VDNFeeValue}
   * @memberof VDNFee
   */
  value: VDNFeeValue
}
