/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL integer representation
 * @export
 * @interface VDNInteger
 */
export interface VDNInteger {
  /**
   *
   * @type {string}
   * @memberof VDNInteger
   */
  type: 'integer'
  /**
   *
   * @type {string}
   * @memberof VDNInteger
   */
  value: string
}
