/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendQuoteValue } from './vdnlend-quote-value'

/**
 * VXL lend_quote representation
 * @export
 * @interface VDNLendQuote
 */
export interface VDNLendQuote {
  /**
   *
   * @type {string}
   * @memberof VDNLendQuote
   */
  type: VDNLendQuoteTypeEnum
  /**
   *
   * @type {VDNLendQuoteValue}
   * @memberof VDNLendQuote
   */
  value: VDNLendQuoteValue
}

export const VDNLendQuoteTypeEnum = {
  LendQuote: 'lend_quote',
} as const

export type VDNLendQuoteTypeEnum = typeof VDNLendQuoteTypeEnum[keyof typeof VDNLendQuoteTypeEnum]
