/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendSupplyQuoteValue } from './vdnlendsupply-quote-value'

/**
 * VXL lend_quote representation
 * @export
 * @interface VDNLendSupplyQuote
 */
export interface VDNLendSupplyQuote {
  /**
   *
   * @type {string}
   * @memberof VDNLendSupplyQuote
   */
  type: 'lend_supply_quote'
  /**
   *
   * @type {VDNLendSupplyQuoteValue}
   * @memberof VDNLendSupplyQuote
   */
  value: VDNLendSupplyQuoteValue
}
