/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNList } from './vdnlist'
import { VDNNone } from './vdnnone'
import { VDNPercentage } from './vdnpercentage'
import { VDNString } from './vdnstring'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNLPQuoteValue
 */
export interface VDNLPQuoteValue {
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPQuoteValue
   */
  after_amounts: VDNList
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPQuoteValue
   */
  after_pct: VDNPercentage
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPQuoteValue
   */
  after_value: VDNDecimal
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPQuoteValue
   */
  assets: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPQuoteValue
   */
  before_amounts: VDNList
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPQuoteValue
   */
  before_pct: VDNPercentage
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPQuoteValue
   */
  before_value: VDNDecimal
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNLPQuoteValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNLPQuoteValueLabel}
   * @memberof VDNLPQuoteValue
   */
  label: VDNLabel | VDNNone
  /**
   *
   * @type {VDNString}
   * @memberof VDNLPQuoteValue
   */
  name: VDNString
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNLPQuoteValue
   */
  quote_asset: VDNAsset
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNLPQuoteValue
   */
  venue: VDNVenue
}
