/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBoolean } from './vdnboolean'
import { VDNDecimal } from './vdndecimal'

/**
 *
 * @export
 * @interface VDNLPPoolRangeValue
 */
export interface VDNLPPoolRangeValue {
  /**
   *
   * @type {VDNBoolean}
   * @memberof VDNLPPoolRangeValue
   */
  in_range: VDNBoolean
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPoolRangeValue
   */
  lower: VDNDecimal
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPoolRangeValue
   */
  price: VDNDecimal
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPoolRangeValue
   */
  upper: VDNDecimal
}
