/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNLPPoolValue } from './vdnlppool-value'

/**
 * VXL lp_pool representation
 * @export
 * @interface VDNLPPool
 */
export interface VDNLPPool extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNLPPool
   */
  type: 'lp_pool'
  /**
   *
   * @type {VDNLPPoolValue}
   * @memberof VDNLPPool
   */
  value: VDNLPPoolValue
}
