/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNDecimal } from './vdndecimal'
import { VDNLPPool } from './vdnlppool'
import { VDNLPQuoteValueLabel } from './vdnlpquote-value-label'
import { VDNList } from './vdnlist'
import { VDNPercentage } from './vdnpercentage'

/**
 *
 * @export
 * @interface VDNLPQuoteValue
 */
export interface VDNLPQuoteValue {
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPQuoteValue
   */
  amounts: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPQuoteValue
   */
  amounts_delta: VDNList
  /**
   *
   * @type {VDNLPQuoteValueLabel}
   * @memberof VDNLPQuoteValue
   */
  label: VDNLPQuoteValueLabel
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPQuoteValue
   */
  ownership: VDNPercentage
  /**
   *
   * @type {VDNLPPool}
   * @memberof VDNLPQuoteValue
   */
  pool: VDNLPPool
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNLPQuoteValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPQuoteValue
   */
  value: VDNDecimal
}
