/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNLPPoolRangeValue } from './vdnlppool-range-value'

/**
 * VXL lp_pool_range representation
 * @export
 * @interface VDNLPPoolRange
 */
export interface VDNLPPoolRange extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNLPPoolRange
   */
  type: 'lp_pool_range'
  /**
   *
   * @type {VDNLPPoolRangeValue}
   * @memberof VDNLPPoolRange
   */
  value: VDNLPPoolRangeValue
}
