/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNPercent } from './vdnpercentage'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNLendPositionValue
 */
export interface VDNLendPositionValue {
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNLendPositionValue
   */
  asset: VDNAsset
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNLendPositionValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNLendPositionValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLendPositionValue
   */
  supplied_amount: VDNDecimal
  /**
   *
   * @type {VDNPercent}
   * @memberof VDNLendPositionValue
   */
  supply_apy: VDNPercent
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNLendPositionValue
   */
  venue: VDNVenue
}
