/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendMarketValue } from './vdnlend-market-value'

/**
 * VXL lend_market representation
 * @export
 * @interface VDNLendMarket
 */
export interface VDNLendMarket {
  /**
   *
   * @type {string}
   * @memberof VDNLendMarket
   */
  type: 'lend_market'
  /**
   *
   * @type {VDNLendMarketValue}
   * @memberof VDNLendMarket
   */
  value: VDNLendMarketValue
}
