/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendPositionValue } from './vdnlend-position-value'

/**
 * VXL lend_supplied representation
 * @export
 * @interface VDNLendPosition
 */
export interface VDNLendPosition {
  /**
   *
   * @type {string}
   * @memberof VDNLendPosition
   */
  type: 'lend_position'
  /**
   *
   * @type {VDNLendPositionValue}
   * @memberof VDNLendPosition
   */
  value: VDNLendPositionValue
}
