/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendSuppliedValue } from './vdnlend-supplied-value'

/**
 * VXL lend_supplied representation
 * @export
 * @interface VDNLendSupplied
 */
export interface VDNLendSupplied {
  /**
   *
   * @type {string}
   * @memberof VDNLendSupplied
   */
  type: 'lend_supplied'
  /**
   *
   * @type {VDNLendSuppliedValue}
   * @memberof VDNLendSupplied
   */
  value: VDNLendSuppliedValue
}
