/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNList } from './vdnlist'
import { VDNLPPoolType } from './vdnlppool-type'
import { VDNPercentage } from './vdnpercentage'
import { VDNString } from './vdnstring'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNLPPositionValue
 */
export interface VDNLPPositionValue {
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPositionValue
   */
  amounts: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPositionValue
   */
  assets: VDNList
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNLPPositionValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNLPPositionValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPositionValue
   */
  lp_amount: VDNDecimal
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNLPPositionValue
   */
  lp_asset: VDNAsset
  /**
   *
   * @type {VDNString}
   * @memberof VDNLPPositionValue
   */
  name: VDNString
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPPositionValue
   */
  ownership: VDNPercentage
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPPositionValue
   */
  pool_fee: VDNPercentage
  /**
   *
   * @type {VDNLPPoolType}
   * @memberof VDNLPPositionValue
   */
  pool_type: VDNLPPoolType
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNLPPositionValue
   */
  quote_asset: VDNAsset
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPositionValue
   */
  target_weights: VDNList
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPositionValue
   */
  value: VDNDecimal
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNLPPositionValue
   */
  venue: VDNVenue
}
