/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from "./vdnbase"

/**
 * VXL LocalFunctionCall representation
 * @export
 * @interface VDNLocalFunctionCall
 */
export interface VDNLocalFunctionCall extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNLocalFunctionCall
   */
  type: 'local_function_call'
  /**
   *
   * @type {null}
   * @memberof VDNLocalFunctionCall
   */
  value: null
}
