/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLabelValue } from './vdnlabel-value'

/**
 * VXL label representation
 * @export
 * @interface VDNLabel
 */
export interface VDNLabel {
  /**
   *
   * @type {string}
   * @memberof VDNLabel
   */
  type: 'label'
  /**
   *
   * @type {VDNLabelValue}
   * @memberof VDNLabel
   */
  value: VDNLabelValue
}
