/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBoolean } from './vdnboolean'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNLendMarket } from './vdnlend-market'

/**
 *
 * @export
 * @interface VDNLendPositionValue
 */
export interface VDNLendPositionValue {
  /**
   *
   * @type {VDNBoolean}
   * @memberof VDNLendPositionValue
   */
  collateral_enabled: VDNBoolean
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNLendPositionValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNLendMarket}
   * @memberof VDNLendPositionValue
   */
  market: VDNLendMarket
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNLendPositionValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLendPositionValue
   */
  supplied_amount: VDNDecimal
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLendPositionValue
   */
  value: VDNDecimal
}
