/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdn-base'
import { VDNLPQuoteValue } from './vdnlpquote-value'

/**
 * VXL lp_quote representation
 * @export
 * @interface VDNLPQuote
 */
export interface VDNLPQuote  extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNLPQuote
   */
  type: 'lp_quote'
  /**
   *
   * @type {VDNLPQuoteValue}
   * @memberof VDNLPQuote
   */
  value: VDNLPQuoteValue
}
