/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdn-base'
import { VDNLPPositionValue } from './vdnlpposition-value'

/**
 * VXL lp_position representation
 * @export
 * @interface VDNLPPosition
 */
export interface VDNLPPosition extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNLPPosition
   */
  type: 'lp_position'
  /**
   *
   * @type {VDNLPPositionValue}
   * @memberof VDNLPPosition
   */
  value: VDNLPPositionValue
}
