/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAsset } from './vdnasset'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNLendSupplyQuoteValue
 */
export interface VDNLendSupplyQuoteValue {
  /**
   *
   * @type {VDNAsset}
   * @memberof VDNLendSupplyQuoteValue
   */
  asset: VDNAsset
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNLendSupplyQuoteValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLendSupplyQuoteValue
   */
  supply_apy: VDNDecimal
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNLendSupplyQuoteValue
   */
  venue: VDNVenue
}
