/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAddress } from './vdnaddress'
import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLPPoolType } from './vdnlppool-type'
import { VDNList } from './vdnlist'
import { VDNPercentage } from './vdnpercentage'
import { VDNString } from './vdnstring'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNLPPoolValue
 */
export interface VDNLPPoolValue {
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPoolValue
   */
  assets: VDNList
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNLPPoolValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNLPPoolValue
   */
  liquidity: VDNDecimal
  /**
   *
   * @type {VDNString}
   * @memberof VDNLPPoolValue
   */
  name: VDNString
  /**
   *
   * @type {VDNAddress}
   * @memberof VDNLPPoolValue
   */
  pool_address: VDNAddress
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNLPPoolValue
   */
  pool_fee: VDNPercentage
  /**
   *
   * @type {VDNLPPoolType}
   * @memberof VDNLPPoolValue
   */
  pool_type: VDNLPPoolType
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNLPPoolValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPoolValue
   */
  reserve_amounts: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPoolValue
   */
  reserve_ratios: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNLPPoolValue
   */
  target_weights: VDNList
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNLPPoolValue
   */
  venue: VDNVenue
}
