/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendRateValue } from './vdnlend-rate-value'

/**
 * VXL lend_quote representation
 * @export
 * @interface VDNLendRate
 */
export interface VDNLendRate {
  /**
   *
   * @type {string}
   * @memberof VDNLendRate
   */
  type: 'lend_rate'
  /**
   *
   * @type {VDNLendRateValue}
   * @memberof VDNLendRate
   */
  value: VDNLendRateValue
}
