/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNLendBorrowQuoteValue } from './vdnlendborrow-quote-value'

/**
 * VXL borrow_quote representation
 * @export
 * @interface VDNLendBorrowQuote
 */
export interface VDNLendBorrowQuote {
  /**
   *
   * @type {string}
   * @memberof VDNLendBorrowQuote
   */
  type: 'lend_borrow_quote'
  /**
   *
   * @type {VDNLendBorrowQuoteValue}
   * @memberof VDNLendBorrowQuote
   */
  value: VDNLendBorrowQuoteValue
}
