/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VDNAsset } from './vdnasset';
import { VDNBlockchain } from './vdnblockchain';
import { VDNDecimal } from './vdndecimal';
import { VDNLabel } from './vdnlabel';
import { VDNVenue } from './vdnvenue';

/**
 * 
 * @export
 * @interface VDNLendBorrowedValue
 */
export interface VDNLendBorrowedValue {
    /**
     * 
     * @type {VDNAsset}
     * @memberof VDNLendBorrowedValue
     */
    'asset': VDNAsset;
    /**
     * 
     * @type {VDNBlockchain}
     * @memberof VDNLendBorrowedValue
     */
    'blockchain': VDNBlockchain;
    /**
     * 
     * @type {VDNDecimal}
     * @memberof VDNLendBorrowedValue
     */
    'borrow_apy': VDNDecimal;
    /**
     * 
     * @type {VDNDecimal}
     * @memberof VDNLendBorrowedValue
     */
    'debt_amount': VDNDecimal;
    /**
     * 
     * @type {VDNLabel}
     * @memberof VDNLendBorrowedValue
     */
    'label': VDNLabel;
    /**
     * 
     * @type {VDNVenue}
     * @memberof VDNLendBorrowedValue
     */
    'venue': VDNVenue;
}

