/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL lp_pool_type representation
 * @export
 * @interface VDNLPPoolType
 */
export interface VDNLPPoolType {
  /**
   *
   * @type {string}
   * @memberof VDNLPPoolType
   */
  type: 'lp_pool_type'
  /**
   *
   * @type {string}
   * @memberof VDNLPPoolType
   */
  value: string
}
