/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAddress } from './vdnaddress'
import { VDNDateTime } from './vdndate-time'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNLabelValue
 */
export interface VDNLabelValue {
  /**
   *
   * @type {VDNAddress}
   * @memberof VDNLabelValue
   */
  address: VDNAddress
  /**
   *
   * @type {VDNDateTime}
   * @memberof VDNLabelValue
   */
  created_at: VDNDateTime
  /**
   *
   * @type {VDNString}
   * @memberof VDNLabelValue
   */
  name: VDNString
}
