/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL object map representation
 * @export
 * @interface VDNMap
 */
export interface VDNMap {
  /**
   *
   * @type {string}
   * @memberof VDNMap
   */
  type: 'map'
  /**
   *
   * @type {object}
   * @memberof VDNMap
   */
  value: Record<string, unknown>
}
