/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNInteger } from './vdninteger'
import { VDNNFTCollection } from './vdnnftcollection'

/**
 *
 * @export
 * @interface VDNNFTValue
 */
export interface VDNNFTValue {
  /**
   *
   * @type {VDNNFTCollection}
   * @memberof VDNNFTValue
   */
  collection: VDNNFTCollection
  /**
   *
   * @type {VDNInteger}
   * @memberof VDNNFTValue
   */
  id: VDNInteger
}
