/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from "./vdnbase"

/**
 * VXL None representation
 * @export
 * @interface VDNNone
 */
export interface VDNNone extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNNone
   */
  type: 'none'
  /**
   *
   * @type {any}
   * @memberof VDNNone
   */
  value?: undefined
}
