/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAddress } from './vdnaddress'
import { VDNBlockchain } from './vdnblockchain'
import { VDNString } from './vdnstring'

/**
 *
 * @export
 * @interface VDNNFTCollectionValue
 */
export interface VDNNFTCollectionValue {
  /**
   *
   * @type {VDNAddress}
   * @memberof VDNNFTCollectionValue
   */
  address: VDNAddress
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNNFTCollectionValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNString}
   * @memberof VDNNFTCollectionValue
   */
  name: VDNString
}
