/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNNFTValue } from './vdnnftvalue'

/**
 * VXL nft representation
 * @export
 * @interface VDNNFT
 */
export interface VDNNFT {
  /**
   *
   * @type {string}
   * @memberof VDNNFT
   */
  type: 'nft'
  /**
   *
   * @type {VDNNFTValue}
   * @memberof VDNNFT
   */
  value: VDNNFTValue
}
