/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNNFTCollectionValue } from './vdnnftcollection-value'

/**
 * VXL nft_collection representation
 * @export
 * @interface VDNNFTCollection
 */
export interface VDNNFTCollection {
  /**
   *
   * @type {string}
   * @memberof VDNNFTCollection
   */
  type: 'nft_collection'
  /**
   *
   * @type {VDNNFTCollectionValue}
   * @memberof VDNNFTCollection
   */
  value: VDNNFTCollectionValue
}
