/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuntimeError, RuntimeSignatureMismatchError } from '../error'
import { VDN } from './vdn'


/**
 * @type VDNOrRuntimeError
 * VDN or RuntimeError
 * @export
 */
export type VDNOrRuntimeError = RuntimeError | RuntimeSignatureMismatchError | VDN
