/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNDecimal } from './vdndecimal'
import { VDNNone } from './vdnnone'
import { VDNPercentage } from './vdnpercentage'

/**
 *
 * @export
 * @interface VDNPriceValue
 */
export interface VDNPriceValue {
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNPriceValue
   */
  asset: VDNAssetSymbol
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNPriceValue
   */
  change_1h: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPriceValueChange1h}
   * @memberof VDNPriceValue
   */
  change_1y: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNPriceValue
   */
  change_24h: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNPriceValue
   */
  change_30d: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNPercentage}
   * @memberof VDNPriceValue
   */
  change_7d: VDNPercentage | VDNNone
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNPriceValue
   */
  market_cap: VDNDecimal | VDNNone
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNPriceValue
   */
  price: VDNDecimal
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNPriceValue
   */
  quote_asset: VDNAssetSymbol
}
