/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNPositionValue } from './vdnposition-value'

/**
 * VXL position representation
 * @export
 * @interface VDNPosition
 */
export interface VDNPosition extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNPosition
   */
  type: 'position'
  /**
   *
   * @type {VDNPositionValue}
   * @memberof VDNPosition
   */
  value: VDNPositionValue
}
