/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VDNAssetSymbol } from './vdnasset-symbol';
import { VDNDecimal } from './vdndecimal';

/**
 * 
 * @export
 * @interface VDNPriceValue
 */
export interface VDNPriceValue {
    /**
     * 
     * @type {VDNAssetSymbol}
     * @memberof VDNPriceValue
     */
    'asset': VDNAssetSymbol;
    /**
     * 
     * @type {VDNDecimal}
     * @memberof VDNPriceValue
     */
    'price': VDNDecimal;
    /**
     * 
     * @type {VDNAssetSymbol}
     * @memberof VDNPriceValue
     */
    'quote_asset': VDNAssetSymbol;
}

