/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'

/**
 * VXL position_type representation
 * @export
 * @interface VDNPositionType
 */
export interface VDNPositionType extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNPositionType
   */
  type: 'position_type'
  /**
   *
   * @type {string}
   * @memberof VDNPositionType
   */
  value: string
}
