/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNAssetSymbol } from './vdnasset-symbol'
import { VDNBlockchain } from './vdnblockchain'
import { VDNDecimal } from './vdndecimal'
import { VDNLabel } from './vdnlabel'
import { VDNList } from './vdnlist'
import { VDNPositionType } from './vdnposition-type'
import { VDNVenue } from './vdnvenue'

/**
 *
 * @export
 * @interface VDNPositionValue
 */
export interface VDNPositionValue {
  /**
   *
   * @type {VDNList}
   * @memberof VDNPositionValue
   */
  amounts: VDNList
  /**
   *
   * @type {VDNList}
   * @memberof VDNPositionValue
   */
  assets: VDNList
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNPositionValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNLabel}
   * @memberof VDNPositionValue
   */
  label: VDNLabel
  /**
   *
   * @type {VDNAssetSymbol}
   * @memberof VDNPositionValue
   */
  quote_asset: VDNAssetSymbol
  /**
   *
   * @type {VDNPositionType}
   * @memberof VDNPositionValue
   */
  type: VDNPositionType
  /**
   *
   * @type {VDNDecimal}
   * @memberof VDNPositionValue
   */
  value: VDNDecimal
  /**
   *
   * @type {VDNVenue}
   * @memberof VDNPositionValue
   */
  venue: VDNVenue
}
