/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNQuoteValue } from './vdn-quote-value'

/**
 * VXL sell_quote representation
 * @export
 * @interface VDNSellQuote
 */
export interface VDNSellQuote extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNSellQuote
   */
  type: 'sell_quote'
  /**
   *
   * @type {VDNQuoteValue}
   * @memberof VDNSellQuote
   */
  value: VDNQuoteValue
}
