/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from "./vdn-base"

/**
 * VXL Success representation
 * @export
 * @interface VDNSuccess
 */
export interface VDNSuccess extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNSuccess
   */
  type: 'success'
  /**
   *
   * @type {any}
   * @memberof VDNSuccess
   */
  value: any
}
