/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL stream representation
 * @export
 * @interface VDNStream
 */
export interface VDNStream {
  /**
   *
   * @type {string}
   * @memberof VDNStream
   */
  type: VDNStreamTypeEnum
  /**
   *
   * @type {string}
   * @memberof VDNStream
   */
  value: string
}

export const VDNStreamTypeEnum = {
  Stream: 'stream',
} as const

export type VDNStreamTypeEnum = typeof VDNStreamTypeEnum[keyof typeof VDNStreamTypeEnum]
