/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL transaction_type representation
 * @export
 * @interface VDNTransactionType
 */
export interface VDNTransactionType {
  /**
   *
   * @type {string}
   * @memberof VDNTransactionType
   */
  type: 'transaction_type'
  /**
   *
   * @type {string}
   * @memberof VDNTransactionType
   */
  value: string
}
