/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBlockchain } from './vdnblockchain'
import { VDNDateTime } from './vdndate-time'
import { VDNString } from './vdnstring'
import { VDNTransactionState } from './vdntransaction-state'
import { VDNTransactionType } from './vdntransaction-type'
import { VDNTransactionValueExplorer } from './vdntransaction-value-explorer'
import { VDNTransactionValueLabel } from './vdntransaction-value-label'

/**
 *
 * @export
 * @interface VDNTransactionValue
 */
export interface VDNTransactionValue {
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNTransactionValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNTransactionValueExplorer}
   * @memberof VDNTransactionValue
   */
  explorer: VDNTransactionValueExplorer
  /**
   *
   * @type {VDNString}
   * @memberof VDNTransactionValue
   */
  expression: VDNString
  /**
   *
   * @type {VDNTransactionValueExplorer}
   * @memberof VDNTransactionValue
   */
  hash: VDNTransactionValueExplorer
  /**
   *
   * @type {VDNString}
   * @memberof VDNTransactionValue
   */
  id: VDNString
  /**
   *
   * @type {VDNTransactionValueLabel}
   * @memberof VDNTransactionValue
   */
  label: VDNTransactionValueLabel
  /**
   *
   * @type {VDNTransactionState}
   * @memberof VDNTransactionValue
   */
  state: VDNTransactionState
  /**
   *
   * @type {VDNDateTime}
   * @memberof VDNTransactionValue
   */
  state_updated_at: VDNDateTime
  /**
   *
   * @type {VDNTransactionType}
   * @memberof VDNTransactionValue
   */
  type: VDNTransactionType
}
