/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBlockchain } from './vdnblockchain'
import { VDNString } from './vdnstring'
import { VDNURL } from './vdnurl'

/**
 *
 * @export
 * @interface VDNTransactionHashValue
 */
export interface VDNTransactionHashValue {
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNTransactionHashValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNURL}
   * @memberof VDNTransactionHashValue
   */
  explorer_url: VDNURL
  /**
   *
   * @type {VDNString}
   * @memberof VDNTransactionHashValue
   */
  hash: VDNString
}
