/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNNone } from './vdnnone'
import { VDNString } from './vdnstring'

/**
 * @type VDNTransactionValueExplorer
 * @export
 */
export type VDNTransactionValueExplorer = VDNNone | VDNString
