/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdn-base'
import { VDNURLValue } from './vdnurlvalue'

/**
 * VXL url representation
 * @export
 * @interface VDNURL
 */
export interface VDNURL extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNURL
   */
  type: 'url'
  /**
   *
   * @type {VDNURLValue}
   * @memberof VDNURL
   */
  value: VDNURLValue
}
