/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
import { VDNVenueValue } from './vdnvenue-value'

/**
 * VXL venue representation
 * @export
 * @interface VDNVenue
 */
export interface VDNVenue extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNVenue
   */
  type: 'venue'
  /**
   *
   * @type {VDNVenueValue}
   * @memberof VDNVenue
   */
  value: VDNVenueValue
}
