/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBlockchain } from './vdnblockchain'
import { VDNString } from './vdnstring'
import { VDNURL } from './vdnurl'
import { VDNVenueSymbol } from './vdnvenue-symbol'
import { VDNVenueType } from './vdnvenue-type'

/**
 *
 * @export
 * @interface VDNVenueValue
 */
export interface VDNVenueValue {
  /**
   *
   * @type {VDNBlockchain}
   * @memberof VDNVenueValue
   */
  blockchain: VDNBlockchain
  /**
   *
   * @type {VDNString}
   * @memberof VDNVenueValue
   */
  name: VDNString
  /**
   *
   * @type {VDNVenueSymbol}
   * @memberof VDNVenueValue
   */
  symbol: VDNVenueSymbol
  /**
   *
   * @type {VDNVenueType}
   * @memberof VDNVenueValue
   */
  type: VDNVenueType
  /**
   *
   * @type {VDNURL}
   * @memberof VDNVenueValue
   */
  website: VDNURL
}
