/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from './vdnbase'
/**
 * VXL code representation
 * @export
 * @interface VDNVXL
 */
export interface VDNVXL extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNVXL
   */
  type: 'vxl'
  /**
   *
   * @type {string}
   * @memberof VDNVXL
   */
  value: string
}
