/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VDNBase } from "./vdnbase"

/**
 * VXL venue_type representation
 * @export
 * @interface VDNVenueType
 */
export interface VDNVenueType extends VDNBase {
  /**
   *
   * @type {string}
   * @memberof VDNVenueType
   */
  type: 'venue_type'
  /**
   *
   * @type {string}
   * @memberof VDNVenueType
   */
  value: string
}
