/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VXL venue_symbol representation
 * @export
 * @interface VDNVenueSymbol
 */
export interface VDNVenueSymbol {
  /**
   *
   * @type {string}
   * @memberof VDNVenueSymbol
   */
  type: 'venue_symbol'
  /**
   *
   * @type {string}
   * @memberof VDNVenueSymbol
   */
  value: string
}
