/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * On-chain venue
 * @export
 * @interface Venue
 */
export interface Venue {
  /**
   * Venue id
   * @type {string}
   * @memberof Venue
   */
  id: string
  /**
   * Venue name
   * @type {string}
   * @memberof Venue
   */
  name: string
  /**
   * Venue url
   * @type {string}
   * @memberof Venue
   */
  type: string
}
