/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents VXL commands that act on a given output
 * @export
 * @interface VXLAction
 */
export interface VXLAction {
  /**
   * Action ID
   * @type {string}
   * @memberof VXLAction
   */
  id: string
  /**
   * Action Type
   * @type {string}
   * @memberof VXLAction
   */
  type: string
  /**
   * Action Name
   * @type {string}
   * @memberof VXLAction
   */
  name: string
  /**
   * Action VXL command
   * @type {string}
   * @memberof VXLAction
   */
  vxl: string
}
