/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to submit VXL to be executed
 * @export
 * @interface VXLSubmitRequest
 */
export interface VXLSubmitRequest {
  /**
   * Is local VXL submission
   * @type {boolean}
   * @memberof VXLSubmitRequest
   */
  local?: boolean
  /**
   * Should results be returned as streams (when possible)
   * @type {boolean}
   * @memberof VXLSubmitRequest
   */
  stream?: boolean
  /**
   * VXL command
   * @type {string}
   * @memberof VXLSubmitRequest
   */
  vxl: string
}
