/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnionType } from './union-type'
import { VDNType } from './vdn'
import { VDNList } from './vdnlist'

/**
 * @type VXLType
 * VXL Type
 * @export
 */
export type VXLType = VDNType | VDNList | UnionType
