/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VXLGenericParameters } from "./vxlgeneric-parameters"

/**
 * Describes the type of a task
 * @export
 * @interface VXLTaskType
 */
export interface VXLTaskType extends VXLGenericParameters {
  /**
   *
   * @type {string}
   * @memberof VXLTaskType
   */
  type: 'task'
}
