/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response for VXL validation
 * @export
 * @interface VXLValidateResponse
 */
export interface VXLValidateResponse {
  /**
   * Response for multiple VXL validation errors
   * @type {Array<object>}
   * @memberof VXLValidateResponse
   */
  errors: Array<object>
}
