/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios'
import { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setBearerAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base'
// @ts-ignore
import { Signature } from '../models'
/**
 * SignaturesApi - axios parameter creator
 * @export
 */
export const SignaturesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Submits signatures for a signing request
     * @summary Submits signatures
     * @param {string} signatureId Signature ID
     * @param {Array<Signature>} signature Signature
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    submit: async (
      signatureId: string,
      signature: Array<Signature>,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'signatureId' is not null or undefined
      assertParamExists('submit', 'signatureId', signatureId)
      // verify required parameter 'signature' is not null or undefined
      assertParamExists('submit', 'signature', signature)
      const localVarPath = `/signatures/submit/{signature_id}`.replace(
        `{${'signature_id'}}`,
        encodeURIComponent(String(signatureId)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication authorization required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(signature, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * SignaturesApi - functional programming interface
 * @export
 */
export const SignaturesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SignaturesApiAxiosParamCreator(configuration)
  return {
    /**
     * Submits signatures for a signing request
     * @summary Submits signatures
     * @param {string} signatureId Signature ID
     * @param {Array<Signature>} signature Signature
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async submit(
      signatureId: string,
      signature: Array<Signature>,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.submit(signatureId, signature, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
  }
}

/**
 * SignaturesApi - factory interface
 * @export
 */
export const SignaturesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = SignaturesApiFp(configuration)
  return {
    /**
     * Submits signatures for a signing request
     * @summary Submits signatures
     * @param {string} signatureId Signature ID
     * @param {Array<Signature>} signature Signature
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    submit(signatureId: string, signature: Array<Signature>, options?: any): AxiosPromise<void> {
      return localVarFp.submit(signatureId, signature, options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * SignaturesApi - object-oriented interface
 * @export
 * @class SignaturesApi
 * @extends {BaseAPI}
 */
export class SignaturesApi extends BaseAPI {
  /**
   * Submits signatures for a signing request
   * @summary Submits signatures
   * @param {string} signatureId Signature ID
   * @param {Array<Signature>} signature Signature
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SignaturesApi
   */
  public submit(signatureId: string, signature: Array<Signature>, options?: AxiosRequestConfig) {
    return SignaturesApiFp(this.configuration)
      .submit(signatureId, signature, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
