/* tslint:disable */
/* eslint-disable */
/**
 * vektor
 * Vektor API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosInstance, AxiosPromise, AxiosRequestConfig } from 'axios'

import { BASE_PATH, BaseAPI, RequestArgs } from '../base'
import {
  assertParamExists,
  createRequestFunction,
  DUMMY_BASE_URL,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common'
import { Configuration } from '../configuration'
import { Stream , StreamPatchParams } from '../models'
/**
 * StreamsApi - axios parameter creator
 * @export
 */
export const StreamsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Delete a single stream
     * @summary Delete streams
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    _delete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('_delete', 'id', id)
      const localVarPath = `/streams/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication authorization required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Patch a single stream
     * @summary Patch a stream
     * @param {string} id Stream ID
     * @param {StreamPatchParams} [streamPatchParams] Stream patch params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    delete2: async (
      id: string,
      streamPatchParams?: StreamPatchParams,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('delete2', 'id', id)
      const localVarPath = `/streams/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication authorization required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(streamPatchParams, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Show details for a single stream
     * @summary Show a stream\'s properties
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('get', 'id', id)
      const localVarPath = `/streams/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication authorization required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Lists all user\'s open streams
     * @summary List open streams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    list: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/streams`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication authorization required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      const headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * StreamsApi - functional programming interface
 * @export
 */
export const StreamsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = StreamsApiAxiosParamCreator(configuration)
  return {
    /**
     * Delete a single stream
     * @summary Delete streams
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async _delete(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator._delete(id, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     * Patch a single stream
     * @summary Patch a stream
     * @param {string} id Stream ID
     * @param {StreamPatchParams} [streamPatchParams] Stream patch params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async delete2(
      id: string,
      streamPatchParams?: StreamPatchParams,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.delete2(id, streamPatchParams, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     * Show details for a single stream
     * @summary Show a stream\'s properties
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async get(
      id: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Stream>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.get(id, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     * Lists all user\'s open streams
     * @summary List open streams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async list(
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Stream>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.list(options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
  }
}

/**
 * StreamsApi - factory interface
 * @export
 */
export const StreamsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = StreamsApiFp(configuration)
  return {
    /**
     * Delete a single stream
     * @summary Delete streams
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    _delete(id: string, options?: any): AxiosPromise<void> {
      return localVarFp._delete(id, options).then((request) => request(axios, basePath))
    },
    /**
     * Patch a single stream
     * @summary Patch a stream
     * @param {string} id Stream ID
     * @param {StreamPatchParams} [streamPatchParams] Stream patch params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    delete2(id: string, streamPatchParams?: StreamPatchParams, options?: any): AxiosPromise<void> {
      return localVarFp.delete2(id, streamPatchParams, options).then((request) => request(axios, basePath))
    },
    /**
     * Show details for a single stream
     * @summary Show a stream\'s properties
     * @param {string} id Stream ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    get(id: string, options?: any): AxiosPromise<Stream> {
      return localVarFp.get(id, options).then((request) => request(axios, basePath))
    },
    /**
     * Lists all user\'s open streams
     * @summary List open streams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    list(options?: any): AxiosPromise<Array<Stream>> {
      return localVarFp.list(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * StreamsApi - object-oriented interface
 * @export
 * @class StreamsApi
 * @extends {BaseAPI}
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
/**
 *
 */
export class StreamsApi extends BaseAPI {
  /**
   * Delete a single stream
   * @summary Delete streams
   * @param {string} id Stream ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StreamsApi
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  public _delete(id: string, options?: AxiosRequestConfig) {
    return StreamsApiFp(this.configuration)
      ._delete(id, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Patch a single stream
   * @summary Patch a stream
   * @param {string} id Stream ID
   * @param {StreamPatchParams} [streamPatchParams] Stream patch params
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StreamsApi
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  public delete2(id: string, streamPatchParams?: StreamPatchParams, options?: AxiosRequestConfig) {
    return StreamsApiFp(this.configuration)
      .delete2(id, streamPatchParams, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Show details for a single stream
   * @summary Show a stream\'s properties
   * @param {string} id Stream ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StreamsApi
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  public get(id: string, options?: AxiosRequestConfig) {
    return StreamsApiFp(this.configuration)
      .get(id, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Lists all user\'s open streams
   * @summary List open streams
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StreamsApi
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  /**
   *
   */
  public list(options?: AxiosRequestConfig) {
    return StreamsApiFp(this.configuration)
      .list(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
